In [4]:
import torch

在开始使用PyTorch时应该了解的主要元素：

* PyTorch张量

* 数学运算

* Autograd模块

* Optim模块

* 神经网络模块

下面让我们依次介绍这些元素吧。

## 一、PyTorch张量
张量只是多维数组。PyTorch中的的张量类似于numpy的ndarrays，另外，张量也可以在GPU上使用。PyTorch支持各种类型的张量。

### 1.1Tensor的数据类型
### 1.1.1 torch.FloatTensor

In [19]:
#指定纬度
a = torch.FloatTensor(2,3)
print(a)
print("\n b:")

#按照给定列表生成浮点型的Tensor
b = torch.FloatTensor([2,3,4,5])
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

 b:
tensor([2., 3., 4., 5.])


### 1.1.2 torch.IntTensor 
用于生成数据类型为整型的Tensor，传递torch.IntTensor的参数可以是一个列表，也可以是表示纬度的元组。

In [20]:
a = torch.IntTensor(2, 3)
print(a)
b = torch.IntTensor([5, 6, 7, 8])
print("\n b:")
print(b)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

 b:
tensor([5, 6, 7, 8], dtype=torch.int32)


### 1.1.3 torch.rand
用于生成数据类型为浮点型且维度指定的随机Tensor，和在Numpy中使用的numpy.rand生成随机数的方法类似，随机生成的浮点数据在0~1区间均匀分布。

In [22]:
a = torch.rand(2,3)
print(a)

tensor([[0.7617, 0.8165, 0.5766],
        [0.3291, 0.0191, 0.6009]])


### 1.1.4 torch.randn
用于数据类型为浮点型且维度指定的随机Tensor，和在Numpy中使用的Numpy.randn生成的随机数的方法类似，随机生成的浮点数的取值满足均值为0，方差为1的正态分布。

In [23]:
a = torch.randn(2, 3)
print(a)

tensor([[-0.9301, -1.3113,  0.5000],
        [ 0.1787,  0.2772, -0.5851]])


### 1.1.5 torch.arange 
torch.range已经被弃用

用于生成数据类型为浮点型且自定义开始范围和结束范围的Tensor，所以传递给torch.range的参数有三个，分别是范围的起始值，范围的结束值和步长，其中，步长用于指定从起始值到结束值得每步的数据间隔。

In [26]:
a = torch.arange(1, 10, 1)
print(a)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


### 1.1.6 torch.zeros
用于生成数据类型为浮点型且维度指定的Tensor，不过这个浮点型的Tensor中的元素全部为0.

In [27]:
a = torch.zeros(2, 3)
print(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


### 1.2 Tensor的运算

### 1.2.1 torch.mul
将参数传递到torch.mul后返回输入参数求积的结果作为输出，参与运算的参数可以全部是Tensor数据类型的变量，也可以是Tensor数据类型的变量和标量的组合

In [30]:
a = torch.randn(2,3)
print("a:")
print(a)

b = torch.randn(2,3)
print("\n b:")
print(b)

print("\ntorch.mul(a,b):")
c = torch.mul(a, b)
print(c)

a:
tensor([[ 4.6872e-01,  3.2202e-01,  2.4221e+00],
        [ 8.1761e-01, -2.1217e-03, -1.1340e+00]])

 b:
tensor([[-0.4322,  1.5551, -1.3506],
        [-1.2597, -0.6036,  2.1189]])

torch.mul(a,b):
tensor([[-2.0258e-01,  5.0076e-01, -3.2714e+00],
        [-1.0299e+00,  1.2807e-03, -2.4028e+00]])


### 1.2.2 torch. mm
将参数传递到torch.mm后返回输入参数的求积结果作为输出，不过这个求积的方式和之前的torch.mul运算方式不太一样，torch.mm运用矩阵之间的乘法规则进行计算，所以被传入的参数会被当作矩阵进行处理，参数的维度自然也要满足矩阵乘法的前提条件，即前一个矩阵的行数必须和后一个矩阵的列数相等，否则不能进行计算。

In [32]:
a = torch.randn(3,2)
print(a)
b = torch.randn(2,3)
print("\nb:")
print(b)

c = torch.mm(a, b)
print("\ntorch.mm(a,b):")
print(c)

tensor([[-1.0622, -2.0696],
        [ 0.2198,  0.0640],
        [-0.2105,  0.8796]])

b:
tensor([[-2.0049,  2.2201, -0.5509],
        [ 0.2837, -1.5067,  1.9639]])

torch.mm(a,b):
tensor([[ 1.5425,  0.7603, -3.4794],
        [-0.4225,  0.3916,  0.0046],
        [ 0.6716, -1.7927,  1.8434]])


### 1.2.3 torch.mv
将参数传递到torch.mv后返回输入参数的求积结果作为输出，torch.mv运用矩阵与向量之间的乘法法则进行计算，被传入的参数中第1个参数代表矩阵，第2个参数代表向量，顺序不能颠倒。

In [33]:
a = torch.randn(2,3)
print("a:")
print(a)

b = torch.randn(3)
print("\nb:")
print(b)

c = torch.mv(a,b)
print("\ntorch.mv(a,b):")
print(c)

a:
tensor([[-0.2934,  0.0307, -0.2456],
        [-1.1221, -1.3581, -0.9236]])

b:
tensor([-1.7865, -0.0162,  0.2873])

torch.mv(a,b):
tensor([0.4530, 1.7612])


## 二、数学运算
与numpy一样，科学计算库非常重要的一点是能够实现高效的数学功能。而PyTorch提供了一个类似的接口，可以使用200个以上的数学运算。

In [6]:
a = torch.FloatTensor([2])
b = torch.FloatTensor([3])
a + b

tensor([5.])

还可以在定义的PyTorch张量上执行各种矩阵运算

In [7]:
matrix = torch.randn(3,3)
matrix

tensor([[ 0.7731, -0.5575,  1.4147],
        [-0.5859,  0.4719, -1.6255],
        [-0.5798,  0.4868, -0.9457]])

In [8]:
matrix.t()

tensor([[ 0.7731, -0.5859, -0.5798],
        [-0.5575,  0.4719,  0.4868],
        [ 1.4147, -1.6255, -0.9457]])

## 三、Autograd模块
PyTorch使用了一种叫做自动微分的技术。也就是说，它会有一个记录我们所有执行操作的记录器，之后再回放记录来计算我们的梯度。这一技术在构建神经网络时尤其有效，因为我们可以通过计算前路参数的微分来节省时间。


In [9]:
from torch.autograd import Variable

In [10]:
x = Variable(train_x)
y = Variable(train_y, requires_grad = False)

NameError: name 'train_x' is not defined

## 四、Optim模块
torch.optim是一个实现各种优化算法的模块，用于构建神经网络。它支持大多数常用的方法，因此我们不必从头开始构建它们。